# Generated by Django 2.0.3 on 2020-11-26 08:58

import datetime
from django.db import migrations, models
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201126_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 16, 58, 34, 922638), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='banner',
            name='display',
            field=models.SmallIntegerField(choices=[(0, '不展示'), (1, '展示')], default=0, verbose_name='是否展示'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=stdimage.models.StdImageField(default=None, upload_to=stdimage.utils.UploadToUUID(path='static/banner/2020/11'), verbose_name='轮播图'),
        ),
    ]
