# Generated by Django 2.0.3 on 2020-11-26 09:30

import datetime
from django.db import migrations, models
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201126_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 17, 30, 26, 759989), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=stdimage.models.StdImageField(default=None, upload_to=stdimage.utils.UploadToUUID(path='banner/2020/11'), verbose_name='轮播图'),
        ),
    ]
