# Generated by Django 2.0.3 on 2020-11-26 09:58

import datetime
from django.db import migrations, models
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201126_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 17, 58, 38, 926775), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=stdimage.models.StdImageField(default=None, upload_to=stdimage.utils.UploadToUUID(path='banner/20201126-175838'), verbose_name='轮播图'),
        ),
    ]
