# Generated by Django 2.0.3 on 2020-11-26 10:52

import datetime
from django.db import migrations, models
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201126_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 18, 52, 10, 61442), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=stdimage.models.StdImageField(default=None, upload_to=stdimage.utils.UploadToUUID(path='banner/'), verbose_name='轮播图'),
        ),
    ]
