# Generated by Django 2.0.3 on 2020-11-27 06:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201126_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '所属标签分类',
                'verbose_name_plural': '所属标签分类',
                'db_table': 'label',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, '葡萄酒'), (2, '白兰地'), (3, '洋酒')], default=1, verbose_name='酒种')),
                ('name', models.CharField(max_length=10, verbose_name='标签分类')),
            ],
            options={
                'verbose_name': '标签分类',
                'verbose_name_plural': '标签分类',
                'db_table': 'tag',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 14, 37, 30, 47666), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='label',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Tag', verbose_name='所属标签分类'),
        ),
    ]
