# Generated by Django 2.0.3 on 2020-11-27 09:01

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201127_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('image', stdimage.models.StdImageField(default=None, upload_to=stdimage.utils.UploadToUUID(path='goods/'), verbose_name='商品图')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('price_range', models.SmallIntegerField(choices=[(1, '0-50'), (2, '50-200'), (3, '200-500'), (4, '500-1000'), (5, '1000以上')], default=1, verbose_name='价格区间')),
                ('standard', models.SmallIntegerField(choices=[(1, '单瓶'), (2, '礼盒'), (3, '整箱')], default=1, verbose_name='规格')),
                ('type', models.SmallIntegerField(choices=[(1, '葡萄酒'), (2, '白兰地'), (3, '洋酒')], default=1, verbose_name='酒种')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='商品详情')),
                ('status', models.SmallIntegerField(choices=[(0, '下架'), (1, '上架')], default=0, verbose_name='是否上架')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 11, 27, 17, 1, 45, 913753), verbose_name='创建时间')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Label', verbose_name='商品标签')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Tag', verbose_name='标签分类')),
            ],
            options={
                'verbose_name': '商品管理',
                'verbose_name_plural': '商品管理',
                'db_table': 'goods',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 17, 1, 45, 908752), verbose_name='创建时间'),
        ),
    ]
