# Generated by Django 2.0.3 on 2020-12-24 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201127_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=50, verbose_name='欲购商品')),
                ('name', models.CharField(max_length=10, verbose_name='客户姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='客户电话')),
                ('wish', models.CharField(max_length=100, verbose_name='意向内容')),
                ('trace', models.CharField(default='', max_length=200, null=True, verbose_name='跟进')),
            ],
            options={
                'verbose_name': '意向池',
                'verbose_name_plural': '意向池',
                'db_table': 'wish',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 14, 50, 32, 437866), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 14, 50, 32, 437866), verbose_name='创建时间'),
        ),
    ]
