# Generated by Django 2.0.3 on 2020-11-29 04:55

import datetime
from django.db import migrations, models
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201129_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='index_position',
            field=models.SmallIntegerField(choices=[(1, '新品推荐'), (2, '整箱特惠'), (3, '礼盒推荐'), (4, '单瓶推荐')], default=1, verbose_name='首页位置'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 12, 55, 15, 898412), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=stdimage.models.StdImageField(blank=True, default=None, null=True, upload_to=stdimage.utils.UploadToUUID(path='banner/'), verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 12, 55, 15, 900407), verbose_name='创建时间'),
        ),
    ]
