# Generated by Django 2.0.3 on 2020-12-24 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201224_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishpool',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 14, 51, 36, 849831), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 14, 51, 36, 849831), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 14, 51, 36, 849831), verbose_name='创建时间'),
        ),
    ]
