# Generated by Django 2.0.3 on 2020-12-24 06:54

import datetime
from django.db import migrations, models
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201224_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 14, 54, 44, 120081), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=stdimage.models.StdImageField(blank=True, default=None, null=True, upload_to=stdimage.utils.UploadToUUID(path='banner/'), verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 14, 54, 44, 120081), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=stdimage.models.StdImageField(blank=True, default=None, null=True, upload_to=stdimage.utils.UploadToUUID(path='goods/'), verbose_name='商品图'),
        ),
        migrations.AlterField(
            model_name='wishpool',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 14, 54, 44, 120081), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wishpool',
            name='trace',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='跟进'),
        ),
    ]
