# Generated by Django 2.0.3 on 2020-12-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201224_1454'),
        ('shop', '0011_auto_20201129_1255'),
    ]

    operations = [
    ]
