# Generated by Django 2.0.3 on 2020-12-25 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_merge_20201225_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='index_position',
        ),
        migrations.AddField(
            model_name='goods',
            name='hot',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否爆款推荐'),
        ),
        migrations.AddField(
            model_name='goods',
            name='index_display',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否首页展示'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 15, 51, 43, 678209), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 15, 51, 43, 682209), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wishpool',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 15, 51, 43, 683209), verbose_name='创建时间'),
        ),
    ]
